[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    mikalhart/TinyGPSPlus@^1.1.0
    knolleary/PubSubClient@^2.8.0
    bblanchon/ArduinoJson@^7.2.1

build_flags =
    -DWIFI_SSID=\"RoadMesh\"
    -DWIFI_PASSWORD=\"roadmesh123\"
    -DMQTT_SERVER=\"192.168.1.100\"
    -DMQTT_PORT=1883
