events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    upstream roadmesh_server {
        server server:3000;
    }

    server {
        listen 80;
        server_name localhost;

        # Express Admin Dashboard & REST API
        location / {
            proxy_pass http://roadmesh_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # WebSocket proxy upgrade
        location /ws {
            proxy_pass http://roadmesh_server/ws;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}
